#!/bin/bash

# This file describes the right status bar, which shows system status via Conky
# The conky output itself is descripbet in ./conky_dzen

# Grab the variables passed in from calling this
foreground=$1
background=$2
font=$3
xmonadStatusWidth=$4
statusBarHeight=$5
trayerWidth=$6

primaryMonitorDimensionAndPosition=$(xrandr | grep "connected primary" | egrep -o "[0-9]+x[0-9]+\+[0-9]+\+[0-9]+")
primaryMonitorXWidth=$(echo $primaryMonitorDimensionAndPosition | cut -d '+' -f1 | cut -d 'x' -f1)
primaryMonitorXPos=$(echo $primaryMonitorDimensionAndPosition | cut -d '+' -f2)
primaryMonitorYPos=$(echo $primaryMonitorDimensionAndPosition | cut -d '+' -f3)
statusPosX=$((primaryMonitorXPos+xmonadStatusWidth))
statusPosY=$primaryMonitorYPos
statusWidth=$((primaryMonitorXWidth-xmonadStatusWidth-trayerWidth))

# The right status bar
conky -qc $HOME/.xmonad/conky_dzen | dzen2 -x $statusPosX -w $statusWidth -h $statusBarHeight -bg $background -fg $foreground -y $statusPosY -fn $font -e 'button3=' -dock &

trayer --monitor primary --edge top --align right --expand false --SetDockType true --SetPartialStrut true --widthtype pixel --width $trayerWidth --heighttype pixel --height $statusBarHeight --transparent false --tint 0xD6C3B6 &
