#!/bin/bash

# This file describes the right status bar, which shows system status via Conky
# The conky output itself is descripbet in ./conky_dzen

# Grab the variables passed in from calling this
foreground=$1
background=$2
font=$3
xmonadStatusWidth=$4
statusBarHeight=$5


#host=$(hostname)
#xWidth=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1)
#Yaxis=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f2)

## Couldn't get -xs and -ta to do the job for the second bar, but the first one provides the struts,
## so I'm just going to leave it, seems to work.
xWidth=$(xrandr | grep "LVDS1 connected" | cut -d ' ' -f3 | cut -d '+' -f1 | cut -d 'x' -f1)
posy=$(xrandr | grep "LVDS1 connected" | cut -d ' ' -f 3 | cut -d '+' -f3)
statusWidth=$((xWidth-xmonadStatusWidth-trayerWidth))
conky -qc $HOME/.xmonad/conky_dzen | dzen2 -x $xmonadStatusWidth -w $statusWidth -h $statusBarHeight -ta 'r' -bg $background -fg $foreground -y $posy -fn $font -e 'button3=' -dock &

# Check to see if external is connected
#if [[ -z `xrandr | grep " connected" | grep 'VGA'` ]]; then
#  conky -qc $HOME/.xmonad/conky_dzen | dzen2 -x $xmonadStatusWidth -w $xWidth -h '19' -ta 'r' -bg $background -fg $foreground -y '0' -fn $font -dock &
  #conky -qc $HOME/.xmonad/conky_dzen1 | dzen2 -x '0' -w '300' -h '14' -ta 'l' -bg $background -fg $foreground -y '0' -fn $font -dock &
#else 
  #nitrogen --restore
#  conky -qc $HOME/.xmonad/conky_dzen | dzen2 -x '1200' -w '720' -h '14' -ta 'r' -bg $background -fg $foreground -y '0' -fn $font -dock &
  #conky -qc $HOME/.xmonad/conky_dzen1 | dzen2 -x '0' -w '720' -h '14' -ta 'l' -bg $background -fg $foreground -y '0' -fn $font -dock &
  #conky -qc $HOME/.xmonad/.conky_dzen2 | dzen2 -x '1200' -w '720' -h '14' -ta 'r' -bg $background -fg $foreground -y '0' -fn $font -dock &
  #conky -qc $HOME/.xmonad/.conky_dzen3 | dzen2 -x '1200' -w '720' -h '14' -ta 'r' -bg $background -fg $foreground -y '0' -fn $font -dock &
#fi
